import { FitnessProgram, ProgramBundle } from '@/types/shop';
import { calculatePricing } from './programs-data';

// All 35 Programs (7 tracks × 5 levels)
export const PROGRAMS: FitnessProgram[] = [
  // RED - STRENGTH & CONDITIONING
  {
    id: 'strength-starter',
    track: 'strength-conditioning',
    level: 'starter',
    name: 'Strength Foundations',
    tagline: 'Build your base strength',
    description: 'Master fundamental movement patterns and build a solid strength foundation',
    pricing: calculatePricing(49),
    features: ['Progressive strength programs', 'Form video library', 'Basic nutrition guidelines', 'Community forum access', 'Monthly group Q&A'],
    benefits: ['Improved strength', 'Better movement quality', 'Injury prevention'],
    isInviteOnly: false,
  },
  {
    id: 'strength-advanced',
    track: 'strength-conditioning',
    level: 'advanced',
    name: 'Strength Builder',
    tagline: 'Accelerate your gains',
    description: 'Advanced programming for serious strength development',
    pricing: calculatePricing(99),
    features: ['Periodized training', 'Video form analysis (monthly)', 'Custom macros', 'Private community', 'Bi-weekly check-ins', 'Supplement protocols'],
    benefits: ['Rapid strength gains', 'Optimized recovery', 'Performance tracking'],
    isInviteOnly: false,
    badge: 'Popular',
  },
  {
    id: 'strength-pro',
    track: 'strength-conditioning',
    level: 'pro',
    name: 'Strength Pro',
    tagline: 'Professional-grade programming',
    description: 'Elite strength systems used by professional athletes',
    pricing: calculatePricing(199),
    features: ['Fully customized training', 'Weekly video analysis', 'Personalized nutrition', 'Direct coach messaging', 'Advanced metrics', 'Competition prep'],
    benefits: ['Elite-level strength', 'Optimized performance', 'Competition readiness'],
    isInviteOnly: false,
  },
  {
    id: 'strength-fancy',
    track: 'strength-conditioning',
    level: 'fancy',
    name: 'Strength Private',
    tagline: 'Your personal strength coach',
    description: 'One-on-one coaching with unlimited support',
    pricing: calculatePricing(399),
    features: ['Daily personalized programming', 'Unlimited video analysis', '24/7 coach access', 'Weekly video calls', 'Custom meal planning', 'Equipment consulting', 'Injury management'],
    benefits: ['Maximum results', 'Personalized attention', 'Fastest progress'],
    maxParticipants: 20,
    isInviteOnly: false,
  },
  {
    id: 'strength-elite',
    track: 'strength-conditioning',
    level: 'elite',
    name: 'Strength Elite',
    tagline: 'The pinnacle of strength training',
    description: 'Invitation-only program for elite performers',
    pricing: calculatePricing(799),
    features: ['World-class coaching team', 'Real-time adjustments', 'Biomechanics analysis', 'Exclusive training camps', 'Sponsor partnerships', 'Media training', 'Recovery technology'],
    benefits: ['World-class performance', 'Elite network', 'Career advancement'],
    maxParticipants: 10,
    isInviteOnly: true,
    badge: 'Invite Only',
  },

  // ORANGE - PERFORMANCE TRAINING
  {
    id: 'performance-starter',
    track: 'performance-training',
    level: 'starter',
    name: 'Performance Basics',
    tagline: 'Unlock your athletic potential',
    description: 'Foundational athletic development for all sports',
    pricing: calculatePricing(59),
    features: ['Sport-agnostic training', 'Speed & agility drills', 'Power development', 'Movement screening', 'Community challenges'],
    benefits: ['Improved athleticism', 'Better coordination', 'Injury resilience'],
    isInviteOnly: false,
  },
  {
    id: 'performance-advanced',
    track: 'performance-training',
    level: 'advanced',
    name: 'Performance Plus',
    tagline: 'Train like an athlete',
    description: 'Advanced athletic development programming',
    pricing: calculatePricing(129),
    features: ['Sport-specific programming', 'Plyometric progressions', 'Olympic lifting', 'Performance testing', 'Bi-weekly coaching', 'Recovery optimization'],
    benefits: ['Enhanced explosiveness', 'Sport-specific gains', 'Competition edge'],
    isInviteOnly: false,
  },
  {
    id: 'performance-pro',
    track: 'performance-training',
    level: 'pro',
    name: 'Performance Pro',
    tagline: 'Professional athletic development',
    description: 'Elite training systems for competitive athletes',
    pricing: calculatePricing(249),
    features: ['Fully customized programs', 'Advanced metrics', 'Video biomechanics', 'Weekly coaching', 'Competition periodization', 'Mental performance'],
    benefits: ['Peak performance', 'Competitive advantage', 'Career longevity'],
    isInviteOnly: false,
    badge: 'Best Value',
  },
  {
    id: 'performance-fancy',
    track: 'performance-training',
    level: 'fancy',
    name: 'Performance Private',
    tagline: 'Elite private coaching',
    description: 'One-on-one elite performance coaching',
    pricing: calculatePricing(499),
    features: ['Daily custom programming', 'Unlimited coach access', 'In-person sessions (monthly)', 'Advanced technology', 'Team coordination', 'Contract support'],
    benefits: ['Maximum performance', 'Professional guidance', 'Career optimization'],
    maxParticipants: 15,
    isInviteOnly: false,
  },
  {
    id: 'performance-elite',
    track: 'performance-training',
    level: 'elite',
    name: 'Performance Elite',
    tagline: 'World-class performance',
    description: 'Invitation-only elite performance program',
    pricing: calculatePricing(999),
    features: ['World-renowned coaching', 'Cutting-edge technology', 'International camps', 'Sponsorship opportunities', 'Media & brand development', 'Legacy programs'],
    benefits: ['World-class results', 'Elite network', 'Legacy creation'],
    maxParticipants: 8,
    isInviteOnly: true,
    badge: 'Invite Only',
  },

  // YELLOW - CARDIO & CORE
  {
    id: 'cardio-starter',
    track: 'cardio-core',
    level: 'starter',
    name: 'Cardio Core Basics',
    tagline: 'Build your engine',
    description: 'Foundation cardio and core stability training',
    pricing: calculatePricing(39),
    features: ['Progressive cardio', 'Core stability routines', 'Breathing techniques', 'Heart rate training', 'Group challenges'],
    benefits: ['Improved endurance', 'Core strength', 'Better conditioning'],
    isInviteOnly: false,
  },
  {
    id: 'cardio-advanced',
    track: 'cardio-core',
    level: 'advanced',
    name: 'Cardio Core Plus',
    tagline: 'Elevate your conditioning',
    description: 'Advanced endurance and core programming',
    pricing: calculatePricing(79),
    features: ['HIIT & LISS protocols', 'Advanced core progressions', 'Metabolic conditioning', 'Performance tracking', 'Monthly coaching'],
    benefits: ['Enhanced endurance', 'Fat loss', 'Athletic conditioning'],
    isInviteOnly: false,
    badge: 'Great Value',
  },
  {
    id: 'cardio-pro',
    track: 'cardio-core',
    level: 'pro',
    name: 'Cardio Core Pro',
    tagline: 'Professional conditioning',
    description: 'Elite endurance and core training systems',
    pricing: calculatePricing(149),
    features: ['Custom conditioning', 'VO2 max optimization', 'Advanced core stability', 'Weekly coaching', 'Race/event prep'],
    benefits: ['Peak conditioning', 'Competition readiness', 'Optimal performance'],
    isInviteOnly: false,
  },
  {
    id: 'cardio-fancy',
    track: 'cardio-core',
    level: 'fancy',
    name: 'Cardio Core Private',
    tagline: 'Personal conditioning coach',
    description: 'One-on-one endurance coaching',
    pricing: calculatePricing(299),
    features: ['Daily custom programming', 'Unlimited support', 'Weekly video sessions', 'Event strategy', 'Recovery protocols'],
    benefits: ['Personalized training', 'Optimal results', 'Expert guidance'],
    maxParticipants: 25,
    isInviteOnly: false,
  },
  {
    id: 'cardio-elite',
    track: 'cardio-core',
    level: 'elite',
    name: 'Cardio Core Elite',
    tagline: 'Elite endurance performance',
    description: 'Invitation-only elite conditioning program',
    pricing: calculatePricing(599),
    features: ['World-class coaching', 'Advanced physiological testing', 'International camps', 'Sponsorship connections', 'Media training'],
    benefits: ['World-class conditioning', 'Elite network', 'Career advancement'],
    maxParticipants: 12,
    isInviteOnly: true,
    badge: 'Invite Only',
  },

  // GREEN - NUTRITION
  {
    id: 'nutrition-starter',
    track: 'nutrition',
    level: 'starter',
    name: 'Nutrition Basics',
    tagline: 'Learn to fuel properly',
    description: 'Foundation nutrition education and meal planning',
    pricing: calculatePricing(29),
    features: ['Basic macro education', 'Meal planning templates', 'Recipe database', 'Shopping guides', 'Community support'],
    benefits: ['Better eating habits', 'Weight management', 'Energy optimization'],
    isInviteOnly: false,
  },
  {
    id: 'nutrition-advanced',
    track: 'nutrition',
    level: 'advanced',
    name: 'Nutrition Plus',
    tagline: 'Optimize your diet',
    description: 'Advanced nutrition coaching and meal planning',
    pricing: calculatePricing(69),
    features: ['Custom macro calculations', 'Personalized meal plans', 'Supplement guidance', 'Monthly coaching', 'Food sensitivity protocols'],
    benefits: ['Optimized nutrition', 'Body composition', 'Performance fuel'],
    isInviteOnly: false,
    badge: 'Popular',
  },
  {
    id: 'nutrition-pro',
    track: 'nutrition',
    level: 'pro',
    name: 'Nutrition Pro',
    tagline: 'Professional nutrition coaching',
    description: 'Elite nutrition systems for peak performance',
    pricing: calculatePricing(139),
    features: ['Fully customized nutrition', 'Weekly coaching', 'Advanced supplementation', 'Performance nutrition timing', 'Body composition tracking'],
    benefits: ['Peak performance nutrition', 'Optimal body comp', 'Recovery optimization'],
    isInviteOnly: false,
  },
  {
    id: 'nutrition-fancy',
    track: 'nutrition',
    level: 'fancy',
    name: 'Nutrition Private',
    tagline: 'Your personal nutritionist',
    description: 'One-on-one nutrition coaching',
    pricing: calculatePricing(279),
    features: ['Daily meal planning', 'Unlimited coach access', 'Weekly video consultations', 'Grocery assistance', 'Restaurant strategies', 'Travel nutrition'],
    benefits: ['Personalized nutrition', 'Maximum results', 'Lifestyle integration'],
    maxParticipants: 30,
    isInviteOnly: false,
  },
  {
    id: 'nutrition-elite',
    track: 'nutrition',
    level: 'elite',
    name: 'Nutrition Elite',
    tagline: 'World-class nutrition',
    description: 'Invitation-only elite nutrition program',
    pricing: calculatePricing(549),
    features: ['Celebrity nutritionist access', 'Advanced metabolic testing', 'Private chef coordination', 'Supplement sponsorships', 'Nutrition research'],
    benefits: ['Elite nutrition', 'Cutting-edge protocols', 'Competitive edge'],
    maxParticipants: 15,
    isInviteOnly: true,
    badge: 'Invite Only',
  },

  // BLUE - MENTAL STAMINA
  {
    id: 'mental-starter',
    track: 'mental-stamina',
    level: 'starter',
    name: 'Mental Basics',
    tagline: 'Build mental toughness',
    description: 'Foundation mental performance training',
    pricing: calculatePricing(39),
    features: ['Mindset training modules', 'Meditation practices', 'Goal setting frameworks', 'Stress management', 'Community support'],
    benefits: ['Mental resilience', 'Better focus', 'Stress reduction'],
    isInviteOnly: false,
  },
  {
    id: 'mental-advanced',
    track: 'mental-stamina',
    level: 'advanced',
    name: 'Mental Plus',
    tagline: 'Strengthen your mind',
    description: 'Advanced mental performance training',
    pricing: calculatePricing(89),
    features: ['Performance psychology', 'Visualization techniques', 'Confidence building', 'Monthly coaching', 'Mental skills tracking'],
    benefits: ['Enhanced focus', 'Competition confidence', 'Mental edge'],
    isInviteOnly: false,
  },
  {
    id: 'mental-pro',
    track: 'mental-stamina',
    level: 'pro',
    name: 'Mental Pro',
    tagline: 'Professional mental training',
    description: 'Elite mental performance systems',
    pricing: calculatePricing(179),
    features: ['Custom mental training', 'Weekly psychology sessions', 'Competition mental prep', 'Performance anxiety management', 'Leadership development'],
    benefits: ['Peak mental performance', 'Competition mastery', 'Leadership skills'],
    isInviteOnly: false,
  },
  {
    id: 'mental-fancy',
    track: 'mental-stamina',
    level: 'fancy',
    name: 'Mental Private',
    tagline: 'Personal sports psychologist',
    description: 'One-on-one mental performance coaching',
    pricing: calculatePricing(349),
    features: ['Daily mental training', 'Unlimited psychologist access', 'Weekly video sessions', 'Crisis intervention', 'Career transition planning'],
    benefits: ['Personalized mental training', 'Maximum mental strength', 'Career support'],
    maxParticipants: 20,
    isInviteOnly: false,
  },
  {
    id: 'mental-elite',
    track: 'mental-stamina',
    level: 'elite',
    name: 'Mental Elite',
    tagline: 'Elite mental performance',
    description: 'Invitation-only elite psychology program',
    pricing: calculatePricing(699),
    features: ['World-renowned psychologists', 'Neurofeedback training', 'Elite mental camps', 'Media pressure management', 'Legacy mindset development'],
    benefits: ['World-class mental game', 'Elite resilience', 'Lasting success'],
    maxParticipants: 10,
    isInviteOnly: true,
    badge: 'Invite Only',
  },

  // PURPLE - RECOVERY
  {
    id: 'recovery-starter',
    track: 'recovery',
    level: 'starter',
    name: 'Recovery Basics',
    tagline: 'Restore and rebuild',
    description: 'Foundation recovery and mobility training',
    pricing: calculatePricing(34),
    features: ['Mobility routines', 'Stretching protocols', 'Sleep optimization', 'Basic recovery tools', 'Community support'],
    benefits: ['Better recovery', 'Injury prevention', 'Improved mobility'],
    isInviteOnly: false,
  },
  {
    id: 'recovery-advanced',
    track: 'recovery',
    level: 'advanced',
    name: 'Recovery Plus',
    tagline: 'Accelerate recovery',
    description: 'Advanced recovery and regeneration protocols',
    pricing: calculatePricing(74),
    features: ['Custom mobility programs', 'Advanced recovery techniques', 'Soft tissue work', 'Monthly coaching', 'Recovery technology guidance'],
    benefits: ['Faster recovery', 'Better performance', 'Injury prevention'],
    isInviteOnly: false,
  },
  {
    id: 'recovery-pro',
    track: 'recovery',
    level: 'pro',
    name: 'Recovery Pro',
    tagline: 'Professional recovery systems',
    description: 'Elite recovery and regeneration protocols',
    pricing: calculatePricing(149),
    features: ['Fully customized recovery', 'Weekly coaching', 'Advanced modality protocols', 'Injury prevention screening', 'Performance recovery tracking'],
    benefits: ['Optimal recovery', 'Peak performance', 'Longevity'],
    isInviteOnly: false,
  },
  {
    id: 'recovery-fancy',
    track: 'recovery',
    level: 'fancy',
    name: 'Recovery Private',
    tagline: 'Personal recovery specialist',
    description: 'One-on-one recovery coaching',
    pricing: calculatePricing(299),
    features: ['Daily recovery programming', 'Unlimited specialist access', 'Weekly video sessions', 'Home recovery setup', 'Injury rehabilitation'],
    benefits: ['Personalized recovery', 'Maximum restoration', 'Expert care'],
    maxParticipants: 25,
    isInviteOnly: false,
  },
  {
    id: 'recovery-elite',
    track: 'recovery',
    level: 'elite',
    name: 'Recovery Elite',
    tagline: 'Elite recovery systems',
    description: 'Invitation-only elite recovery program',
    pricing: calculatePricing(599),
    features: ['World-class specialists', 'Cutting-edge technology', 'Private recovery facilities', 'Advanced regeneration', 'Career longevity planning'],
    benefits: ['World-class recovery', 'Career longevity', 'Elite performance'],
    maxParticipants: 12,
    isInviteOnly: true,
    badge: 'Invite Only',
  },

  // PINK - TEAM SPORTS & GROUP FITNESS
  {
    id: 'team-starter',
    track: 'team-sports',
    level: 'starter',
    name: 'Team Basics',
    tagline: 'Train together, grow together',
    description: 'Foundation group fitness and team training',
    pricing: calculatePricing(44),
    features: ['Group workout programs', 'Team challenges', 'Community events', 'Basic team dynamics', 'Social fitness platform'],
    benefits: ['Community support', 'Motivation', 'Social fitness'],
    isInviteOnly: false,
  },
  {
    id: 'team-advanced',
    track: 'team-sports',
    level: 'advanced',
    name: 'Team Plus',
    tagline: 'Elevate your team',
    description: 'Advanced group training and team development',
    pricing: calculatePricing(94),
    features: ['Advanced group programs', 'Team building activities', 'Competition preparation', 'Monthly team coaching', 'Performance tracking'],
    benefits: ['Team synergy', 'Competition readiness', 'Group accountability'],
    isInviteOnly: false,
    badge: 'Popular',
  },
  {
    id: 'team-pro',
    track: 'team-sports',
    level: 'pro',
    name: 'Team Pro',
    tagline: 'Professional team training',
    description: 'Elite team development and group performance',
    pricing: calculatePricing(189),
    features: ['Custom team programs', 'Weekly team coaching', 'Team psychology sessions', 'Competition strategy', 'Leadership development'],
    benefits: ['Elite team performance', 'Championship mindset', 'Team excellence'],
    isInviteOnly: false,
  },
  {
    id: 'team-fancy',
    track: 'team-sports',
    level: 'fancy',
    name: 'Team Private',
    tagline: 'Private team coaching',
    description: 'Exclusive team coaching and development',
    pricing: calculatePricing(379),
    features: ['Daily team programming', 'Unlimited coach access', 'Weekly team sessions', 'Private facility access', 'Team culture development'],
    benefits: ['Personalized team training', 'Maximum team results', 'Elite culture'],
    maxParticipants: 15,
    isInviteOnly: false,
  },
  {
    id: 'team-elite',
    track: 'team-sports',
    level: 'elite',
    name: 'Team Elite',
    tagline: 'Championship team training',
    description: 'Invitation-only elite team program',
    pricing: calculatePricing(749),
    features: ['World-class coaching staff', 'Championship preparation', 'Elite training camps', 'Team brand development', 'Legacy building'],
    benefits: ['Championship performance', 'Elite team culture', 'Legacy creation'],
    maxParticipants: 10,
    isInviteOnly: true,
    badge: 'Invite Only',
  },
];

// Bundled Packages
export const BUNDLES: ProgramBundle[] = [
  // SINGLE TIER - ALL TRACKS
  {
    id: 'bundle-starter-all',
    name: 'Starter All-Access',
    description: 'All 7 tracks at the Starter level',
    type: 'single-tier-all-tracks',
    tier: 'starter',
    pricing: calculatePricing(199),
    includedPrograms: PROGRAMS.filter(p => p.level === 'starter').map(p => p.id),
    features: ['Access to all 7 training tracks', 'Foundation-level programming', 'Community forum access', 'Monthly group sessions', 'Complete training library'],
    savings: 40,
    badge: 'Best Value',
  },
  {
    id: 'bundle-advanced-all',
    name: 'Advanced All-Access',
    description: 'All 7 tracks at the Advanced level',
    type: 'single-tier-all-tracks',
    tier: 'advanced',
    pricing: calculatePricing(449),
    includedPrograms: PROGRAMS.filter(p => p.level === 'advanced').map(p => p.id),
    features: ['All 7 premium training tracks', 'Advanced programming', 'Private community access', 'Bi-weekly coaching', 'Performance tracking'],
    savings: 35,
    badge: 'Most Popular',
  },
  {
    id: 'bundle-pro-all',
    name: 'Pro Complete',
    description: 'All 7 tracks at the Pro level',
    type: 'single-tier-all-tracks',
    tier: 'pro',
    pricing: calculatePricing(899),
    includedPrograms: PROGRAMS.filter(p => p.level === 'pro').map(p => p.id),
    features: ['All 7 professional tracks', 'Fully customized programming', 'Weekly coaching sessions', 'Advanced performance metrics', 'Competition preparation'],
    savings: 30,
  },
  {
    id: 'bundle-elite-all',
    name: 'Elite Mastery',
    description: 'All 7 tracks at the Elite level',
    type: 'single-tier-all-tracks',
    tier: 'elite',
    pricing: calculatePricing(3599),
    includedPrograms: PROGRAMS.filter(p => p.level === 'elite').map(p => p.id),
    features: ['All 7 elite performance tracks', 'World-class coaching team', 'Exclusive training camps', 'Sponsorship opportunities', 'Legacy building'],
    savings: 20,
    maxParticipants: 10,
    badge: 'Invite Only',
  },

  // SINGLE TRACK - ALL TIERS (Sample - can add more)
  {
    id: 'bundle-strength-all',
    name: 'Strength Complete Journey',
    description: 'All 5 levels of Strength & Conditioning',
    type: 'single-track-all-tiers',
    track: 'strength-conditioning',
    pricing: calculatePricing(799),
    includedPrograms: PROGRAMS.filter(p => p.track === 'strength-conditioning').map(p => p.id),
    features: ['Progressive access to all 5 levels', 'Complete strength development path', 'Lifetime program updates', 'Priority support', 'Elite community access'],
    savings: 45,
  },
  {
    id: 'bundle-performance-all',
    name: 'Performance Complete Journey',
    description: 'All 5 levels of Performance Training',
    type: 'single-track-all-tiers',
    track: 'performance-training',
    pricing: calculatePricing(999),
    includedPrograms: PROGRAMS.filter(p => p.track === 'performance-training').map(p => p.id),
    features: ['Progressive access to all 5 levels', 'Complete athletic development', 'Lifetime program updates', 'Priority support', 'Elite community access'],
    savings: 45,
  },
];
